name: Check

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  CI: true

jobs:
  test:
    name: Run code quality tools and tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Cache pnpm modules
        # Cache depends on number of dependencies in project
        # - For small projects (< 10 deps), cache doesn't make sense and sometimes can be even slower
        # - For big projects (> 100 deps), cache brings good speed advantages
        # Measurement results:
        # https://github.com/actions/setup-node/issues/271#issuecomment-871408337
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # - name: Build packages
      #   run: pnpm build

      - name: Check format
        run: pnpm run check:format

      - name: Lint
        run: pnpm run lint

      - name: Check types
        run: pnpm run check:types

      # - name: Test
      #   run: pnpm run test
